import re

with open('app/dashboard/page.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace(
    'sky: "bg-white",\n    red: "bg-white",\n    amber: "bg-white",',
    'sky: "bg-white dark:bg-slate-900",\n    red: "bg-white dark:bg-slate-900",\n    amber: "bg-white dark:bg-slate-900",'
)

content = content.replace(
    'sky: "bg-sky-50 text-sky-600",\n    red: "bg-red-50 text-red-600",\n    amber: "bg-amber-50 text-amber-600",',
    'sky: "bg-sky-50 dark:bg-sky-900/30 text-sky-600 dark:text-sky-400",\n    red: "bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400",\n    amber: "bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400",'
)

# And checking for the risk badges in the table which are generated via functions
# Wait, riskBadge and stabilityBadge are generated by functions. Let's see them.
